template = "https://github.com/giellalt/template-lang-und"
rev_id = 333
template_sha = "a03015fd00a15a0ad51da907dc4891c29ab9c8b2"

[replacements]
__GLOTTOLOG_ID__ = "nucl1310"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-mya"
__UND2C__ = "my"
__UNDEFINED__ = "Burmese"
__UND__ = "mya"
